name: Build Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove existing vcpkg
        run: rm -rf "$VCPKG_INSTALLATION_ROOT"
        shell: 'bash'
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: octomap qhull fcl opencv eigen3
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgTriplet: x64-windows
          vcpkgGitCommitId: 7bc5b8cdfaf35329c1520b2af8d368e2b1cb78e6
      - name: Setup Environment
        run: |
          choco install -y cmake vcredist2013 vcredist140 openssl boost-msvc-14.2
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/asio.1.12.1.nupkg -OutFile asio.1.12.1.nupkg
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/cunit.2.1.3.nupkg -OutFile cunit.2.1.3.nupkg
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/tinyxml-usestl.2.6.2.nupkg -OutFile tinyxml-usestl.2.6.2.nupkg
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/tinyxml2.6.0.0.nupkg -OutFile tinyxml2.6.0.0.nupkg
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/log4cxx.0.10.0.nupkg -OutFile log4cxx.0.10.0.nupkg
          Invoke-WebRequest https://github.com/ros2/choco-packages/releases/download/2020-02-24/bullet.2.89.0.nupkg -OutFile bullet.2.89.0.nupkg
          choco install -y -s . asio cunit tinyxml-usestl tinyxml2 log4cxx bullet
          Import-Module "C:\ProgramData\chocolatey\helpers\chocolateyProfile.psm1"
          refreshenv
          python -m pip install -U catkin_pkg cryptography empy ifcfg lark-parser lxml netifaces numpy opencv-python pyparsing pyyaml setuptools rosdistro vcstool colcon-common-extensions
      - name: Build
        run: |
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1'
          Invoke-WebRequest https://github.com/ros2/ros2/releases/download/release-foxy-20201211/ros2-foxy-20201211-windows-release.amd64.zip -OutFile ros.zip
          Expand-Archive -Path 'ros.zip' -DestinationPath .
          .\ros2-windows\local_setup.ps1
          mkdir ws/src
          cd ws/src
          Get-Content $env:GITHUB_WORKSPACE/ros2-foxy-moveit2.repos | vcs import
          cd ..
          colcon build --event-handlers console_cohesion+ status- --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=False -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -Wno-dev
