name: Build Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup
        run: |
          choco install -y python --version 3.8.3
          choco install -y vcredist2013 vcredist140 opennsl opencv
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/asio.1.12.1.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/cunit.2.1.3.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/eigen.3.3.4.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/tinyxml-usestl.2.6.2.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/tinyxml2.6.0.0.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/log4cxx.0.10.0.nupkg
          wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/bullet.2.89.0.nupkg
          choco install -y -s . asio cunit eigen tinyxml-usestl tinyxml2 log4cxx bullet
          python -m pip install -U catkin_pkg cryptography empy ifcfg lark-parser lxml netifaces numpy opencv-python pyparsing pyyaml setuptools rosdistro
          