name: Build Foxy

on:
  push:
    branches: main
    paths:
      - ".github/workflows/foxy.yml"
      - "vcpkg.json"
      - "foxy.repos"
  workflow_dispatch:

jobs:
  build-foxy:
    env:
      INSTALL_DIR: "C:/opt/ros/foxy"
      BUILD_DIR: "C/build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg and python
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
          rm -rf "C:/hostedtoolcache/windows/python/"
          WORKSPACE="${{ github.workspace }}"
          mv ${WORKSPACE//\\/$'/'}/vcpkg C:/
          mv ${WORKSPACE//\\/$'/'}/.git C:/
          mv ${WORKSPACE//\\/$'/'}/.gitmodules C:/
          ls -a ${WORKSPACE//\\/$'/'}
          ls -a C:/
        shell: 'bash'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      - name: Install Python Deps
        run: pip install -U vcstool colcon-common-extensions catkin_pkg cryptography EmPy ifcfg lark-parser lxml numpy pyparsing pyyaml
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@dev/always_cache_in_post_action
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgDirectory: 'C:/vcpkg'
          appendedCacheKey: ${{ hashFiles( '/vcpkg.json' ) }}
          vcpkgTriplet: x64-windows
          vcpkgGitCommitId: "2bcc2d07f382e55e140289e0fecfad1f094fb14c"
      - name: Setup Environment
        run: |
          C:/vcpkg/vcpkg.exe install
          mkdir ws/src
          vcs import --input foxy.repos ws/src
      - name: Build
        run: |
          $VCPKG_PATH = "C:/vcpkg"
          cd ws
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1'
          colcon build `
            --merge-install `
            --install-base ${{ env.INSTALL_DIR }} `
            --build-base ${{ env.BUILD_DIR }} `
            --event-handlers console_cohesion+ status- `
            --cmake-args `
              -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DCMAKE_TOOLCHAIN_FILE="$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_MANIFEST_DIR="${{ github.workspace }}" `
              -Wno-dev
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: foxy
          path: ${{ env.INSTALL_DIR }}
