name: Build Foxy

on:
  push:
    branches: main
    paths:
      - ".github/workflows/foxy.yml"
      - "vcpkg.json"
      - "foxy.repos"
  workflow_dispatch:

jobs:
  build-foxy:
    env:
      INSTALL_DIR: "C:/opt/ros/foxy"
      BUILD_DIR: "C:/build"
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg and python
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
          rm -rf "C:/hostedtoolcache/windows/python/"
        shell: 'bash'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      - name: Install Python Deps
        run: pip install -U vcstool colcon-common-extensions catkin_pkg cryptography EmPy ifcfg lark-parser lxml numpy pyparsing pyyaml
      # - name: Cache vcpkg
      #   if: ${{ always() }}
      #   uses: actions/cache@v2
      #   with:
      #     path: C:/vcpkg_installed
      #     key: foxy-${{ hashFiles('/vcpkg.json') }}
      - name: Setup Environment
        working-directory: C:/
        run: |
          Move-Item -Path '${{ github.workspace }}/vcpkg' -Destination C:/vcpkg
          Move-Item -Path '${{ github.workspace }}/vcpkg.json' -Destination C:/vcpkg.json
          mkdir C:/ws/src
          vcs import --input foxy.repos C:/ws/src
          C:/vcpkg/bootstrap-vcpkg.bat
      - name: Setup NuGet Credentials
        working-directory: C:/
        shell: 'bash'
        run: >
          `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/Ace314159/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "Ace314159"
          -password "${{ secrets.GITHUB_TOKEN }}"
      - name: Build
        working-directory: C:/ws
        run: |
          $VCPKG_PATH = "C:/vcpkg"
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1'
          colcon build `
            --merge-install `
            --install-base ${{ env.INSTALL_DIR }} `
            --build-base ${{ env.BUILD_DIR }} `
            --event-handlers console_cohesion+ status- `
            --cmake-args `
              -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DCMAKE_TOOLCHAIN_FILE="$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" `
              -DVCPKG_MANIFEST_DIR="C:/" `
              -Wno-dev
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: foxy
          path: ${{ env.INSTALL_DIR }}
