name: Build Foxy

on:
  push:
    branches: main
    paths:
      - ".github/workflows/foxy.yml"
      - "vcpkg.json"
      - "foxy.repos"
  workflow_dispatch:

jobs:
  build-foxy:
    env:
      FOXY_INSTALL_DIR: "C:/opt/ros/foxy"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg and python
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
          rm -rf "C:/hostedtoolcache/windows/python/"
        shell: 'bash'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      - name: Install Python Deps
        run: pip install -U vcstool colcon-common-extensions catkin_pkg cryptography EmPy ifcfg lark-parser lxml numpy pyparsing pyyaml
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '/vcpkg.json' ) }}
          vcpkgTriplet: x64-windows
          additionalCachedPaths: ${{ github.workspace }}/vcpkg_installed
      - name: Setup Environment
        run: |
          mkdir ws/src
          vcs import --input foxy.repos ws/src
      - name: Build
        run: |
          $VCPKG_PATH = "${{ github.workspace }}/vcpkg"
          $VCPKG_PATH = $VCPKG_PATH -replace "[\\]", "/"
          cd ws
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1'
          > colcon build
            --merge-install
            --install-base ${{ env.FOXY_INSTALL_DIR }}
            --cmake-args
              -DCMAKE_BUILD_TYPE=RelWithDebInfo
              -DCMAKE_TOOLCHAIN_FILE="$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake"
              -DVCPKG_MANIFEST_DIR="${{ github.workspace }}"
              -Wno-dev
            --event-handlers console_cohesion+ status-
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: foxy
          path: ${{ env.FOXY_INSTALL_DIR }}
