name: Mongo

on:
  push:
    branches: main
    paths:
      - .github/workflows/mongo.yml
  workflow_dispatch:

jobs:
  Build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
        shell: bash
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.17'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: mongodb/mongo-cxx-driver
          ref: 26compat
          path: driver
      - name: Build Dependencies
        run: |
          pip install -U setuptools wheel
          pip install scons==2.5.1
          ${{ github.workspace }}/vcpkg/vcpkg.exe install boost-thread boost-filesystem boost-program-options boost-system
      - name: Build Driver
        run: |
          cd ${{ github.workspace }}/driver
          scons --full --use-system-boost --disable-warnings-as-errors
