name: Mongo

on:
  push:
    branches: main
    paths:
      - .github/workflows/mongo.yml
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.17'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: mongodb/mongo-cxx-driver
          ref: 26compat
          path: driver
      - name: Build Mongo CXX Driver
        run: |
        pip install -U setuptools wheel
          pip install scons==2.5.1
          cd ${{ github.workspace }}/driver
          scons --full --disable-warnings-as-errors
