name: Mongo

on:
  push:
    branches: main
    paths:
      - .github/workflows/mongo.yml
  workflow_dispatch:

jobs:
  Build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      INCLUDE: '${{ github.workspace }}/vcpkg/installed/x64-windows/include'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
        shell: bash
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: mongodb/mongo-cxx-driver
          ref: 26compat
          path: driver
      - name: Setup Environment
        run: |
          pip install -U setuptools wheel
          pip install scons==2.5.1
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat
          & (${{ github.workspace }}/vcpkg/vcpkg fetch nuget | Select-Object -Last 1) `
            sources add `
              -source "https://nuget.pkg.github.com/Ace314159/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "Ace314159" `
              -password "${{ secrets.GITHUB_TOKEN }}"
          ${{ github.workspace }}/vcpkg/vcpkg.exe install --triplet=x64-windows `
            boost-thread boost-filesystem boost-program-options boost-system
      - name: Build Driver
        run: |
          'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat'
          cd ${{ github.workspace }}/driver
          scons --full --use-system-boost --disable-warnings-as-errors
        shell: cmd
