name: Build Foxy Workspaces

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Foxy Base"]
    types:
      - completed

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        workspace: [moveit2, nav2]
    env:
      ROS_BASE: C:/opt/ros/foxy
      INSTALL_DIR: C:/opt/ros/foxy/x64
      DEBUG_DIR: C:/opt/ros/debug/x64
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      VCPKG_DEFAULT_TRIPLET: x64-windows-ros2
      VCPKG_OVERLAY_PORTS: '${{ github.workspace }}/overlay-ports'
      VCPKG_OVERLAY_TRIPLETS: '${{ github.workspace }}/overlay-triplets'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Remove existing vcpkg
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"
        shell: 'bash'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      - name: Setup Environment
        working-directory: C:/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -U vcstool colcon-common-extensions catkin_pkg cryptography EmPy ifcfg lark-parser lxml numpy pyparsing pyyaml
          pip install git+https://github.com/colcon/colcon-powershell
          Move-Item -Path '${{ github.workspace }}/vcpkg' -Destination C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat
          nuget sources add `
              -source "https://nuget.pkg.github.com/Ace314159/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "Ace314159" `
              -password "${{ secrets.GITHUB_TOKEN }}"
          mkdir -p C:/vcpkg/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}/
          New-Item -Path ${{ env.INSTALL_DIR }} -ItemType SymbolicLink -Value C:/vcpkg/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}/ -Force
          C:/vcpkg/vcpkg.exe install '@${{ github.workspace }}/deps/${{ matrix.workspace }}.txt'
          Install-Module Pscx -Scope CurrentUser -Force -AllowClobber
          Install-Module 7Zip4Powershell -Scope CurrentUser -Force
          cd ${{ github.workspace }}
          hub release download "ros2-foxy-base"
          Expand-7Zip "ros2-foxy-base.7z" -TargetPath ${{ env.ROS_BASE }}
          Expand-7Zip "ros2-foxy-base.7z" C:/ros2-foxy-base
      - name: Clone Repos
        run: |
          mkdir C:/ws/src
          vcs import --input '${{ github.workspace }}/repos/${{ matrix.workspace }}.repos' C:/ws/src
          $patchFile = '${{ github.workspace }}/patches/${{ matrix.workspace }}.patch'
          if (Test-Path $patchFile) {
            git apply $patchFile --unsafe-paths --directory=C:/ws/src
          }
      - name: Build
        working-directory: C:/ws
        run: |
          Invoke-BatchFile "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ${{ env.INSTALL_DIR }}/local_setup.ps1
          colcon build `
            --merge-install `
            --install-base ${{ env.INSTALL_DIR }} `
            --event-handlers console_cohesion+ status- `
            --cmake-args `
              -G Ninja `
              -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DCMAKE_PDB_OUTPUT_DIRECTORY=${{ env.DEBUG_DIR }}/bin `
              -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} `
              -DBUILD_TESTING=False `
              -DBUILD_EXAMPLES=False `
              -DBUILD_UNIT_TESTS=False `
              -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
              -DCMAKE_SYSTEM_VERSION="10.0.19041.0" `
              -Wno-dev
      - name: Fix Installation
        working-directory: ${{ env.INSTALL_DIR }}
        run: |
          $files = Get-ChildItem -Recurse -File C:/ros2-foxy-base/x64 -Name
          foreach ($file in $files) {
            if (Test-Path $file) {
              Remove-Item $file
            }
          }
          $files = Get-ChildItem -Recurse -Path * -Include *.cmake
          foreach ($file in $files) {
            (Get-Content $file).replace('C:/vcpkg/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}/', 'C:/opt/ros/foxy/x64/') | Set-Content $file
            (Get-Content $file) -replace 'C:/vcpkg/packages/.+/include', 'C:/opt/ros/foxy/x64/include' | Set-Content $file
          }
      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-7Zip -Path C:/opt/ros/foxy -ArchiveFileName "C:/ros2-foxy-${{ matrix.workspace }}.7z" -CompressionLevel Ultra
          Compress-7Zip -Path C:/opt/ros/debug -ArchiveFileName "C:/debug.7z" -CompressionLevel Ultra
          hub release show ros2-foxy-${{ matrix.workspace }} -f "%b" > ${{ github.workspace }}/description.md
          $file = "${{ github.workspace }}/description.md"
          $date = (Get-Date).ToUniversalTime().ToString("MM-dd-yy HH:mm:ss UTC")
          (Get-Content $file) -replace 'Last Updated: .*', "Last Updated: $date" | Set-Content $file
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'C:/ros2-foxy-${{ matrix.workspace }}.7z,C:/debug.7z'
          bodyFile: ${{ github.workspace }}/description.md
          tag: ros2-foxy-${{ matrix.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}
  Combine:
    needs: [Build]
    env:
      ROS_BASE: C:/opt/ros/foxy
      DEBUG_BASE: C:/opt/ros/debug
      WORKSPACES: base;moveit2;nav2
      INSTALL_DIR: C:/opt/ros/foxy/x64
      VCPKG_DEFAULT_TRIPLET: x64-windows-ros2
      VCPKG_OVERLAY_PORTS: '${{ github.workspace }}/overlay-ports'
      VCPKG_OVERLAY_TRIPLETS: '${{ github.workspace }}/overlay-triplets'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download and Combine
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Install-Module 7Zip4Powershell -Scope CurrentUser -Force
          $workspaces = '${{ env.WORKSPACES }}'.split(';')
          foreach ($workspace in $workspaces) {
            hub release download "ros2-foxy-$workspace"
            Expand-7Zip "ros2-foxy-$workspace.7z" -TargetPath ${{ env.ROS_BASE }}
            Expand-7Zip "debug.7z" -TargetPath ${{ env.DEBUG_BASE }}
            Remove-Item -Path "debug.7z"
          }
      - name: Setup vcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat
          nuget sources add `
              -source "https://nuget.pkg.github.com/Ace314159/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "Ace314159" `
              -password "${{ secrets.GITHUB_TOKEN }}"
          ${{ github.workspace }}/vcpkg/vcpkg.exe install ogre
      - name: Fix Installation
        working-directory: ${{ env.INSTALL_DIR }}
        run: |
          $files = Get-ChildItem -Recurse -Path * -Include *.cmake
          foreach ($file in $files) {
            (Get-Content $file).replace('${{ github.workspace }}/vcpkg/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}/', 'C:/opt/ros/foxy/x64/') | Set-Content $file
            (Get-Content $file) -replace '${{ github.workspace }}/vcpkg/packages/.+/include', 'C:/opt/ros/foxy/x64/include' | Set-Content $file
          }
          $files = Get-ChildItem -Path * -Include *.py -Recurse
          foreach ($file in $files) {
            $data = (Get-Content $file)
            if ($data) {
              $data.replace('c:\hostedtoolcache\windows\python\3.8.3\x64\python.exe', 'c:\python38\python.exe') | Set-Content $file
            }
          }
          $files = Get-ChildItem -File -Recurse ${{ github.workspace }}/vcpkg/packages/ogre_${{ env.VCPKG_DEFAULT_TRIPLET }} -Name
          foreach ($file in $files) {
            $fullPath = "C:/opt/ros/foxy/x64/$($file)"
            if (Test-Path $fullPath) {
              Remove-Item $fullPath
            }
          }
      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-7Zip -Path C:/opt/ros/foxy -ArchiveFileName "C:/ros2-foxy-combined.7z" -CompressionLevel Ultra
          Compress-7Zip -Path C:/opt/ros/debug -ArchiveFileName "C:/debug.7z" -CompressionLevel Ultra
          hub release show ros2-foxy-combined -f "%b" > ${{ github.workspace }}/description.md
          $file = "${{ github.workspace }}/description.md"
          $date = (Get-Date).ToUniversalTime().ToString("MM-dd-yy HH:mm:ss UTC")
          (Get-Content $file) -replace 'Last Updated: .*', "Last Updated: $date" | Set-Content $file
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'C:/ros2-foxy-combined.7z,C:/debug.7z'
          bodyFile: ${{ github.workspace }}/description.md
          tag: ros2-foxy-combined
          token: ${{ secrets.GITHUB_TOKEN }}
